### PR TITLE
Include some paths to headers

### PR DESCRIPTION
**Pull request by uncomfyhalomacro**
Any way to make this dynamic across distros since some paths are not standardized? this is pain lol. it works btw.

image

### CODE REVIEW

**Comment by Shinyzenith** [comment]
image

**Comment by Shinyzenith** [comment]
I have not implemented any pixman / xkb calls yet.

**Comment by Shinyzenith** [comment]
also header placements vary from distro to distro, part of the reason why I don't like C too much.. Nothing I can do to fix that...

**Comment by Shinyzenith** [comment]
as for the clang one, we can automate that at build time via make, and then a simple sed command to just change the line. Do not delete the protocols line, we need that for the compiled headers from wayland-scanner.

**Comment by uncomfyhalomacro** [comment]
> I have not implemented any pixman / xkb calls yet.

It fails if i dont add that in openSUSE zzzz

**Comment by uncomfyhalomacro** [comment]
> as for the clang one, we can automate that at build time via make, and then a simple sed command to just change the line. Do not delete the protocols line, we need that for the compiled headers from wayland-scanner.

oh sure hmmm hmmm

**Comment by Shinyzenith** [comment]
I'll try to address this with Meson, AFAIK it has some header detection mechanism.

**Comment by uncomfyhalomacro** [comment]
> I'll try to address this with Meson, AFAIK it has some header detection mechanism.

truth. learn meson. meson is pog

**Comment by uncomfyhalomacro** [comment]
> also header placements vary from distro to distro, part of the reason why I don't like C too much.. Nothing I can do to fix that...

yep thats why the tooling sucks xD. at least solutions (though ugly) exists.

**Comment by Shinyzenith** [comment]
> > also header placements vary from distro to distro, part of the reason why I don't like C too much.. Nothing I can do to fix that...
> 
> yep thats why the tooling sucks xD. at least solutions (though ugly) exists.

Yeah conan bs

**Pull request closed without merging**
